# Generated by Django 3.2.10 on 2026-01-15 10:21

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddTailors',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tailor', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=10, null=True)),
                ('mobile_number', models.CharField(max_length=15, null=True, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_works', models.IntegerField(default=0)),
                ('pending_works', models.IntegerField(default=0)),
                ('upcoming_works', models.IntegerField(default=0)),
                ('completed_works', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Add_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ordered_length', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('length', models.CharField(max_length=15)),
                ('shoulder', models.CharField(max_length=15)),
                ('cloth', models.CharField(max_length=20, null=True)),
                ('sleeve_sada', models.CharField(max_length=15, null=True)),
                ('sleeve_cuff', models.CharField(max_length=15, null=True)),
                ('center_sleeve', models.CharField(max_length=15, null=True)),
                ('collar_type_image_url', models.CharField(max_length=255, null=True)),
                ('pocket_image_url', models.CharField(max_length=255, null=True)),
                ('pocket_type', models.CharField(max_length=15, null=True)),
                ('collar_measurements', models.CharField(max_length=15, null=True)),
                ('cuff_type_image_url', models.CharField(max_length=255, null=True)),
                ('cuff_measurements', models.CharField(max_length=15, null=True)),
                ('collar_type', models.CharField(max_length=15, null=True)),
                ('cuff_type', models.CharField(max_length=15, null=True)),
                ('sleeve_bottom', models.CharField(max_length=15, null=True)),
                ('regal', models.CharField(max_length=15)),
                ('loose', models.CharField(max_length=15)),
                ('pocket', models.CharField(max_length=15)),
                ('seat', models.CharField(max_length=15, null=True)),
                ('total_payment', models.CharField(max_length=15, null=True)),
                ('advance_payment', models.CharField(max_length=15, null=True)),
                ('balance_payment', models.CharField(max_length=15, null=True)),
                ('bottom1', models.CharField(max_length=50)),
                ('button_type', models.CharField(choices=[('makfi', 'Makfi'), ('makfi_bayyin', 'Makfi Bayyin'), ('button_bayyin', 'Button Bayyin'), ('makfi_op', 'Makfi OP'), ('makfi_op_nice', 'Makfi OP Nice'), ('makfi_nice', 'Makfi Nice'), ('makfi_zip', 'Makfi Zip'), ('dabble_zib', 'Dabble Zib')], max_length=15)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=100000, null=True)),
                ('model_details', models.CharField(blank=True, max_length=100000, null=True)),
                ('bill_number', models.CharField(max_length=15, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('pending_or_delivered', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('is_printed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='admin_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_length', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloth_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ordered_length', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('length', models.CharField(max_length=15)),
                ('shoulder', models.CharField(max_length=15)),
                ('cloth', models.CharField(max_length=20, null=True)),
                ('sleeve_sada', models.CharField(max_length=15, null=True)),
                ('sleeve_cuff', models.CharField(max_length=15, null=True)),
                ('center_sleeve', models.CharField(max_length=15, null=True)),
                ('collar_type_image_url', models.CharField(max_length=255, null=True)),
                ('pocket_image_url', models.CharField(max_length=255, null=True)),
                ('collar_measurements', models.CharField(max_length=15, null=True)),
                ('cuff_type_image_url', models.CharField(max_length=255, null=True)),
                ('cuff_measurements', models.CharField(max_length=15, null=True)),
                ('collar_type', models.CharField(max_length=15, null=True)),
                ('pocket_type', models.CharField(max_length=15, null=True)),
                ('cuff_type', models.CharField(max_length=15, null=True)),
                ('sleeve_bottom', models.CharField(max_length=15, null=True)),
                ('regal', models.CharField(max_length=15)),
                ('loose', models.CharField(max_length=15)),
                ('pocket', models.CharField(max_length=15)),
                ('seat', models.CharField(max_length=15, null=True)),
                ('bottom1', models.CharField(max_length=50)),
                ('button_type', models.CharField(choices=[('makfi', 'Makfi'), ('makfi_bayyin', 'Makfi Bayyin'), ('button_bayyin', 'Button Bayyin'), ('makfi_op', 'Makfi OP'), ('makfi_op_nice', 'Makfi OP Nice'), ('makfi_nice', 'Makfi Nice'), ('makfi_zip', 'Makfi Zip'), ('dabble_zib', 'Dabble Zib')], max_length=15)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=100000, null=True)),
                ('model_details', models.CharField(blank=True, max_length=100000, null=True)),
                ('bill_number', models.CharField(max_length=15, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('clothdetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.cloth')),
                ('tailor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='reception_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, null=True)),
                ('item_quantity', models.PositiveIntegerField(null=True)),
                ('item_price', models.FloatField(null=True)),
                ('total_price', models.FloatField(null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.add_order')),
            ],
        ),
        migrations.AddField(
            model_name='add_order',
            name='clothdetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.cloth'),
        ),
        migrations.AddField(
            model_name='add_order',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.customer'),
        ),
        migrations.AddField(
            model_name='add_order',
            name='tailor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
