# Generated by Django 3.2.10 on 2026-01-15 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(default='1', max_length=15)),
                ('length', models.CharField(default='1', max_length=15)),
                ('shoulder', models.CharField(default='1', max_length=15)),
                ('loose', models.CharField(default='1', max_length=15)),
                ('neck', models.CharField(default='1', max_length=15)),
                ('regal', models.CharField(default='1', max_length=15)),
                ('cuf', models.CharField(default='1', max_length=15)),
                ('pocket_size', models.CharField(blank=True, max_length=15, null=True)),
                ('cuftype', models.CharField(choices=[('cuff', 'Cuff'), ('normal', 'Normal')], default='normal', max_length=10)),
                ('sleeve', models.CharField(default='1', max_length=15)),
                ('sleeve_type', models.CharField(choices=[('half_sleeve', 'Half Sleeve'), ('full_sleeve', 'Full Sleeve')], default='half_sleeve', max_length=15)),
                ('bill_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('delivery_date', models.DateField(null=True)),
                ('bottom1', models.CharField(blank=True, default='1', max_length=50, null=True)),
                ('bottom2', models.CharField(blank=True, default='1', max_length=50, null=True)),
                ('button_type', models.CharField(blank=True, choices=[('bayyin_mahfi', 'Bayyin Mahfi'), ('zip_mahfi', 'Zip Mahfi'), ('button_bayyin', 'Button Bayyin')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AddTailor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tailor', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True, unique=True)),
                ('password', models.CharField(max_length=10, null=True)),
                ('mobile_number', models.CharField(max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailors.addcustomer')),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailors.addtailor')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tailors.addcustomer')),
                ('tailor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tailors.addtailor')),
            ],
        ),
        migrations.AddField(
            model_name='addcustomer',
            name='tailor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tailors.addtailor'),
        ),
    ]
